# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release BRS

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - name: Update Phoenix Wallet
        run: |
          cd ./ci
          ./updatePhoenix.sh
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml -U
      - name: Get SHA256 Hash 
        id: hash
        run: |
          cd ./dist
          echo "::set-output name=SHA256::$(sha256sum *.zip)"
      - name: Cut Pre-Release with Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.zip
          file_glob: true
          asset_name: Signum Node ${{github.ref}}
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
          body: |
            Signum node auto-generated pre-release from Github Actions ${{github.ref}}

            SHA-256: `${{ steps.hash.outputs.SHA256 }}`

            New features: <Add here>
